import { StyleSheet } from 'react-native';
import { width, height, Color, FontSize, FontFamily, Border } from "../GlobalStyles";

export const styles = StyleSheet.create({
    progressbar: {
      borderRadius: Border.br_10xs,
      width: width * 339,
      height: height * 9,
    },
    awayTypo: {
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 16,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
    },
    textFlexBox: {
      alignItems: "center",
      display: "flex",
    },
    vsTypo: {
      fontFamily: FontFamily.notoSansExtraBold,
      fontWeight: "800",
      lineHeight:  height * 30,
      fontSize: FontSize.size_11xl,
      color: Color.colorWhite,
      position: "absolute",
    },
    totalLayout: {
      height:  height * 65,
      width: width * 94,
      top:  height * 25,
      position: "absolute",
    },
    homeTypo: {
      top:  height * 25,
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 16,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
      position: "absolute",
    },
    textTypo5: {
      left: width * 73,
      width: width * 25,
      alignItems: "center",
      display: "flex",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      lineHeight:  height * 15,
      letterSpacing: width * -0.3,
      fontSize: FontSize.size_sm,
      textAlign: "left",
      position: "absolute",
    },
    matchLayout: {
      height:  height * 66,
      width: width * 371,
      backgroundColor: Color.colorDarkslategray,
      left: width * 2,
      position: "absolute",
    },
    image563IconLayout: {
      width: width * 375,
      position: "absolute",
    },
    image563ParentPosition: {
      height:  height * 372,
      width: width * 375,
      left: 0,
      top: 0,
      position: "absolute",
    },
    parentLayout: {
      height:  height * 174,
      position: "absolute",
    },
    away2Position: {
      top:  height * 2,
      position: "absolute",
    },
    arsLayout: {
      width: width * 74,
      height:  height * 72,
      position: "absolute",
    },
    arsIconLayout1: {
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    textTypo4: {
      letterSpacing: width * -0.4,
      fontSize: FontSize.size_lg,
      width: width * 88,
      textAlign: "center",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
    },
    text9Position: {
      right: width * 5,
      position: "absolute",
    },
    textTypo3: {
      color: Color.colorSlategray_100,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      position: "absolute",
    },
    mciIcon1Position: {
      left: width * 109,
      top: 0,
    },
    textTypo2: {
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight:  height * 22,
      letterSpacing: width * -0.4,
      fontSize: FontSize.size_lg,
      color: Color.colorWhite,
      textAlign: "left",
      position: "absolute",
    },
    framePosition: {
      top:  height * 165,
      height: width * 9,
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    textClr: {
      color: Color.colorWhite,
      position: "absolute",
    },
    textTypo1: {
      width: width * 76,
      lineHeight:  height * 18,
      letterSpacing: width * -0.4,
      fontSize: FontSize.size_lg,
      alignItems: "center",
      display: "flex",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      top: 0,
      position: "absolute",
    },
    arsIconLayout: {
      height:  height * 25,
      position: "absolute",
    },
    vectorIconLayout: {
      height:  height * 1,
      width: width * 351,
      position: "absolute",
    },
    groupFrameLayout: {
      height:  height * 47,
      width: width * 237,
      left: width * 69,
      position: "absolute",
    },
    textPosition: {
      letterSpacing: width * -0.7,
      marginTop:  height * 1.5,
      top: "48%",
      lineHeight:  height * 17,
      fontSize: FontSize.size_sm,
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      position: "absolute",
    },
    frameChild1Layout: {
      height:  height * 27,
      position: "absolute",
    },
    textTypo: {
      top:  height * 6,
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 14.5,
      fontSize: FontSize.size_smi,
      position: "absolute",
    },
    played: {
      left: width * 141,
      textAlign: "left",
      top: 0,
      position: "absolute",
    },
    draws: {
      textAlign: "right",
      left: 0,
      top: 0,
      position: "absolute",
    },
    text: {
      top:  height * 1,
      width: width * 25,
      color: Color.colorWhite,
      position: "absolute",
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      display: "flex",
      lineHeight: width * 15,
      letterSpacing: width * -0.3,
      fontSize: FontSize.size_sm,
      right: 0,
      textAlign: "left",
    },
    drawsParent: {
      top:  height * 90,
      left: width * 128,
      width: width * 70,
      height:  height * 15,
      position: "absolute",
    },
    text1: {
      top:  height * 42,
      left: width * 133,
      justifyContent: "center",
      width: width * 55,
      textAlign: "center",
      alignItems: "center",
      display: "flex",
      letterSpacing: width * -0.6,
      fontWeight: "800",
      lineHeight:  height * 30,
      fontSize: FontSize.size_11xl,
    },
    totalWins: {
      left: width * 35,
      textAlign: "right",
      top: 0,
      position: "absolute",
    },
    text2: {
      width: width * 25,
      color: Color.colorWhite,
      position: "absolute",
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      display: "flex",
      lineHeight:  height * 15,
      letterSpacing: width * -0.3,
      fontSize: FontSize.size_sm,
      textAlign: "right",
      left: -4,
      top: 0,
    },
    home: {
      left: width * 58,
      textAlign: "right",
    },
    text3: {
      top:  height * 26,
      width: width * 25,
      color: Color.colorWhite,
      position: "absolute",
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      display: "flex",
      lineHeight:  height * 15,
      letterSpacing: width * -0.3,
      fontSize: FontSize.size_sm,
      textAlign: "right",
      left: -4,
    },
    away: {
      top:  height * 50,
      left: width * 62,
      textAlign: "right",
      position: "absolute",
    },
    text4: {
      top:  height * 51,
      width: width * 25,
      color: Color.colorWhite,
      position: "absolute",
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      display: "flex",
      lineHeight: height * 15,
      letterSpacing: width * -0.3,
      fontSize: FontSize.size_sm,
      textAlign: "right",
      left: -4,
    },
    totalWinsParent: {
      left: 0,
    },
    totalWins1: {
      width: width * 65,
      left: 0,
      textAlign: "left",
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 16,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
      top: 0,
      position: "absolute",
    },
    text5: {
      top: 0,
    },
    home1: {
      width: width * 40,
      alignItems: "center",
      display: "flex",
      left: 0,
      textAlign: "left",
    },
    text6: {
      top:  height * 26,
    },
    away1: {
      top:  height * 50,
      width: width * 40,
      left: 0,
      textAlign: "left",
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 16,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
      position: "absolute",
    },
    text7: {
      top:  height * 51,
    },
    totalWinsGroup: {
      left: width * 227,
    },
    playedParent: {
      top:  height * 429,
      width: width * 321,
      height:  height * 105,
      left: width * 27,
      position: "absolute",
    },
    matchChild: {
      top:  height * 590,
    },
    matchItem: {
      top:  height * 728,
    },
    matchInner: {
      top:  height * 866,
    },
    image563Icon: {
      height:  height * 352,
      left: 0,
      top: 0,
    },
    lineargradient1: {
      backgroundColor: "transparent",
    },
    frameChild: {
      width: width * 9,
      height:  height * 15,
    },
    arsChild: {
      height:  height * 72,
      right: 0,
      top: 0,
    },
    arsIcon: {
      right: width * 11,
      height:  height * 72,
      width: width * 74,
      top: 0,
      opacity: 0.9,
    },
    ars: {
      left: width * 240,
      height:  height * 72,
      top:  height * 60,
      width: width * 72,
    },
    mciIcon: {
      left: width * 11,
      height:  height * 72,
      top:  height * 60,
      width: width * 72,
      opacity: 0.9,
    },
    text8: {
      top:  height * 139,
      width: width * 88,
      lineHeight:  height * 22,
      left: width * 5,
      position: "absolute",
    },
    text9: {
      top:  height * 139,
      marginRight: width * 16,
      width: width * 88,
      lineHeight:  height * 22,
      letterSpacing: width * -0.4,
      fontSize: FontSize.size_lg,
      textAlign: "center",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
    },
    nd: {
      marginLeft: width * -165.5,
      left: "50%",
      top:  height * 165,
      color: Color.colorSlategray_100,
      alignItems: "center",
      display: "flex",
      letterSpacing: width * -0.3,
      lineHeight:  height * 15,
      fontSize: FontSize.size_smi,
      width: width * 34,
      textAlign: "right",
    },
    text10: {
      marginLeft: width * -124.5,
      left: "50%",
      top:  height * 165,
      color: Color.colorSlategray_100,
      alignItems: "center",
      display: "flex",
      letterSpacing: width * -0.3,
      lineHeight:  height * 15,
      fontSize: FontSize.size_smi,
      width: width * 64,
      textAlign: "left",
    },
    st: {
      marginLeft: width * 54.5,
      left: "50%",
      top:  height * 165,
      color: Color.colorSlategray_100,
      alignItems: "center",
      display: "flex",
      letterSpacing: width * -0.3,
      lineHeight:  height * 15,
      fontSize: FontSize.size_smi,
      width: width * 34,
      textAlign: "right",
    },
    text11: {
      marginLeft: width * 95.5,
      left: "50%",
      top:  height * 165,
      color: Color.colorSlategray_100,
      alignItems: "center",
      display: "flex",
      letterSpacing: width * -0.3,
      lineHeight:  height * 15,
      fontSize: FontSize.size_smi,
      width: width * 64,
      textAlign: "left",
    },
    text12: {
      top:  height * -2,
      left: width * -9,
    },
    wrapper: {
      left: width * 23,
      width : width * 80,
      height:  height * 16,
      top: 0,
    },
    text13: {
      top:  height * 129,
      lineHeight:  height * 14,
      letterSpacing: width * -0.3,
      width : width * 150,
      fontSize: FontSize.size_sm,
      color: Color.colorSlategray_100,
      textAlign: "left",
      left: 0,
    },
    vs: {
      top:  height * 85,
      letterSpacing: width * 1.5,
      width: width * 45,
      left: width * 28.5,
      textAlign: "center",
    },
    frameParent: {
      width: width * 108,
      height:  height * 143,
      position: "absolute",
    },
    frameItem: {
      left: width * 36,
      height:  height * 9,
    },
    frameInner: {
      left: width * 263,
      height:  height * 9,
    },
    arsParent: {
      left: width * 1,
      width: width * 331,
      top: 0,
    },
    vectorParent: {
      top:  height * 80,
      left: width * 24,
      width: width * 332,
    },
    text14: {
      top:  height * 322,
      left: width * 16,
    },
    etihadStadiumManchester: {
      top:  height * 47,
      left: width * 29.5,
      width: width * 300,
      lineHeight:  height * 16,
      letterSpacing: width * -0.3,
      fontSize: FontSize.size_sm,
      color: Color.colorSlategray_100,
      textAlign: "center",
    },
    text15: {
      top:  height * 563,
      left: width * 16,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 16,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
    },
    rectangleView: {
      top:  height * 350,
      height:  height * 59,
      left: 0,
      backgroundColor: Color.colorGray_100,
      width: width * 375,
    },
    container: {
      top:  height * 388,
      width: width * 339,
      height:  height * 9,
      left: width * 16,
      position: "absolute",
    },
    home2: {
      marginTop:  height * -276.75,
      top: "50%",
      left: 0,
      textAlign: "left",
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 13,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
      position: "absolute",
    },
    away2: {
      right: 0,
      textAlign: "right",
      color: Color.colorLightslategray,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight:  height * 13,
      letterSpacing: width * -0.6,
      fontSize: FontSize.size_smi,
    },
    text16: {
      left: width * 46,
      textAlign: "left",
    },
    mciIcon1: {
      left: width * 109,
      top: 0,
      width: width * 25,
    },
    ars1: {
      width: width * 24,
      left: 0,
      top: 0,
    },
    arsIcon1: {
      width: width * 25,
      left: width * 0,
      height: height *  25,
      top: 0,
    },
    mciParent: {
      top:  height * 257,
      width: width * 134,
      left: width * 105,
      height:  height * 25,
    },
    arsGroup: {
      top:  height * 326,
      width: width * 134,
      left: width * 105,
      height:  height * 25,
    },
    mciGroup: {
      top:  height * 395,
      width: width * 134,
      left: width * 105,
      height:  height * 25,
    },
    mciContainer: {
      top:  height * 533,
      width:width *  134,
      left: width * 105,
      height:  height * 25,
    },
    arsContainer: {
      top:  height * 464,
      width: width * 134,
      left: width * 105,
      height:  height * 25,
    },
    text17: {
      right: width * 42,
      textAlign: "right",
    },
    homeParent: {
      top:  height * 361,
      height:  height * 558,
      width: width * 339,
      left: width * 16,
      position: "absolute",
    },
    vectorIcon: {
      top:  height * 550,
      left: width * 16,
    },
    matchChild1: {
      top:  height * 413,
      left: width * 12,
    },
    text18: {
      left: width * -108,
      width: width * 150,
      textAlign: "right",
    },
    text19: {
      right: width * -108,
      width: width * 150,
      textAlign: "left",
    },
    text20: {
      left: width * 88,
      textAlign: "left",
      color: Color.colorSlategray_100,
      lineHeight:  height * 15,
      fontSize: FontSize.size_smi,
      letterSpacing: width * -0.6,
      top: 0,
    },
    frameChild1: {
      borderRadius: Border.br_9xs,
      backgroundColor: Color.colorGray_200,
      right: 0,
      left: 0,
      top: 0,
    },
    frameChild2: {
      top:  height * 4,
      right: width * 27,
      height:  height * 18,
      left: width * 27,
    },
    text21: {
      left: width * 11,
      textAlign: "left",
    },
    text22: {
      left: width * 35,
      textAlign: "center",
    },
    rectangleParent: {
      top:  height * 20,
      left: width * 91,
      width: width * 55,
    },
    parent: {
      top:  height * 597,
    },
    back: {
        position: "absolute",
        width : width * 50,
        height : height * 50,
        left : width * 4,
        top: height * 2,
    },
    frameGroup: {
      top:  height * 666,
    },
    group: {
      top:  height * 735,
    },
    frameView: {
      top:  height * 873,
    },
    frameContainer: {
      top:  height * 804,
    },
    match: {
      flex: 1,
      width: "100%",
      height:  height * 932,
      overflow: "hidden",
      backgroundColor: Color.colorGray_100,
    },
  });

  export default styles;