import { StyleSheet } from 'react-native';
import { width, height, Color, FontSize, FontFamily, Border } from "../GlobalStyles";

export const styles = StyleSheet.create({
    progressbar: {
      backgroundColor: "#31313c",
    },
    progressbar1: {
      transform: [{ scaleX: -1 }],
      flexDirection: 'row',
      backgroundColor: "#31313c",
    },
    textFlexBox: {
      textAlign: "center",
    },
    parentPosition: {
      flexDirection: "row",
      marginTop: height * 10,
      position: "absolute",
    },
    textTypo3: {
      color: Color.colorSlategray,
      textAlign: "center",
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight: height * 16,
      fontSize: FontSize.size_sm,
    },
    textClr: {
      color: Color.colorWhite,
      position: "absolute",
    },
    textClr1: {
      color: Color.colorWhite,
      position: "absolute",
    },
    iconPosition: {
      height: height * 20,
      width: width * 20,
      top: height * 67,
      marginTop: height * 10,
      position: "absolute",
    },
    groupParentPosition: {
      height: height * 18,
      width: width * 18,
      top: height * 99,
      marginTop: height * 10,
      left: "50%",
      position: "absolute",
    },
    textPosition: {
      top: height * 3,
      marginLeft: width * -6,
      lineHeight: height * 13,
      fontSize: FontSize.size_xs,
      textAlign: "center",
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      left: "50%",
      position: "absolute",
    },
    groupLayout: {
      borderWidth: width * 1,
      borderStyle: "solid",
      borderRadius: Border.br_8xs,
      left: 0,
      top: 0,
      height: height * 18,
      width: width * 18,
      position: "absolute",
    },
    framePosition1: {
      height: height * 6,
      width: width * 6,
      top: height * 97.5,
      marginTop: height * 10,
      position: "absolute",
    },
    groupChild7Layout: {
      width: width * 40,
      height: height * 18,
      position: "absolute",
    },
    textTypo1: {
      fontFamily: FontFamily.robotoBold,
      lineHeight: height * 26,
      fontSize: FontSize.size_3xl,
      fontWeight: "600",
      textAlign: "left",
      color: Color.colorSlategray,
    },
    frameLayout: {
      height: height * 2,
      width: width * 100,
    },
    image505Icon: {
      width: width * 371,
      height: height * 136,
      borderRadius: Border.br_4xs,      
    },
    mainChild1Position: {
      top: height * 153,
      position: "absolute",
    },
    mainChild1: {
      borderRadius: Border.br_4xs,
      justifyContent: 'center',
      width: width * 371,
      height: height * 136, 
      zIndex: 0,
      backgroundColor: Color.colorDarkslategray,
    },
    text: {
      top: height * 100,
      zIndex: 1,
      marginTop: height * 10,
      color: Color.colorLightsteelblue_100,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      lineHeight: height * 16,
      fontSize: FontSize.size_sm,
      width : width * 70,
      textAlign: "center",
      left: width * 150.5,
      position: "absolute",
    },
    text2: {
      marginLeft: width * 32,
    },
    parent: {
      top: height * 30,
      left: width * 109,
      gap: width * 1.7,
      zIndex: 2,
      justifyContent: "center",
      alignItems: "center",
    },
    text5: {
      left: width * 60,
      textAlign: "right",
      zIndex: 3,
      width: width * 55,
      lineHeight: height * 14,
      fontSize: FontSize.size_xs,
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      top: height * 66,
      marginTop: height * 10,
    },
    text6: {
      right: width * 60,
      textAlign: "left",
      zIndex: 4,
      width: width * 55,
      lineHeight: height * 14,
      fontSize: FontSize.size_xs,
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      top: height * 66,
      marginTop: height * 10,
    },
    image538Icon: {
      left: width * 126,
      zIndex: 5,
    },
    image539Icon: {
      right: width * 126,
      zIndex: 6,
    },
    text7: {
      color: Color.colorLightsteelblue_200,
    },
    groupChild: {
      borderColor: Color.colorLightsteelblue_200,
    },
    group: {
      marginLeft: width * -131.5,
      zIndex: 7,
    },
    container: {
      marginLeft: width * -112.5,
      zIndex: 8,
    },
    text9: {
      color: Color.colorLightsteelblue_100,
    },
    groupInner: {
      borderColor: Color.colorLightsteelblue_100,
    },
    groupView: {
      marginLeft: width * -93.5,
      zIndex: 9,
    },
    parent1: {
      marginLeft: width * -74.5,
      zIndex: 10,
    },
    parent2: {
      marginLeft: width * -9,
      top: 0,
      height: height * 18,
      width: width * 18,
      left: "50%",
      position: "absolute",
    },
    groupWrapper: {
      marginLeft: width * -55.5,
      zIndex: 11,
    },
    parent3: {
      marginLeft: width * 38.5,
      zIndex: 12,
    },
    parent4: {
      marginLeft: width * 57.5,
      zIndex: 13,
    },
    parent5: {
      marginLeft: width * 76.5,
      zIndex: 14,
    },
    parent6: {
      marginLeft: width * 95.5,
      zIndex: 15,
    },
    groupContainer: {
      marginLeft: width * 114.5,
      zIndex: 16,
    },
    frameItem: {
      left: width * 222,
      zIndex: 17,
    },
    frameInner: {
      left: width * 144,
      zIndex: 18,
    },
    groupChild7: {
      borderRadius: Border.br_3xs,
      backgroundColor: Color.colorTomato,
      left: width * -5,
      width: width * 40,
      top: 0,
    },
    text17: {
      top: 0,
      height: height * 16,
      width: width * 30,
      lineHeight: height * 16,
      fontSize: FontSize.size_xs,
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      textAlign: "center",
      left: 0,
    },
    rectangleParent: {
      top: height * 5,
      left: width * 318,
      zIndex: 19,
      marginTop: height * 10,
    },
    text18: {
      left: width * -8,
      width: width * 40,
      letterSpacing: width * 1,
      display: "flex",
      fontWeight: "700",
      fontFamily: FontFamily.robotoBold,
      lineHeight: height * 26,
      fontSize: FontSize.size_3xl,
      textAlign: "center",
      color: Color.colorWhite,
      alignItems: "center",
    },
    text19: {
      left: width * 37.5,
      width: width * 40,
      letterSpacing: width * 1,
      display: "flex",
      fontWeight: "700",
      fontFamily: FontFamily.robotoBold,
      lineHeight: height * 26,
      fontSize: FontSize.size_3xl,
      textAlign: "center",
      color: Color.colorWhite,
      alignItems: "center",
    },
    text20: {
      left: width * 82.5,
      width: width * 40,
      letterSpacing: width * 1,
      display: "flex",
      fontWeight: "700",
      fontFamily: FontFamily.robotoBold,
      lineHeight: height * 26,
      fontSize: FontSize.size_3xl,
      textAlign: "center",
      color: Color.colorWhite,
      alignItems: "center",
    },
    text21: {
      left: width * 127,
      width: width * 40,
      letterSpacing: width * 1,
      display: "flex",
      fontWeight: "700",
      fontFamily: FontFamily.robotoBold,
      lineHeight: height * 26,
      fontSize: FontSize.size_3xl,
      textAlign: "center",
      color: Color.colorWhite,
      alignItems: "center",
    },
    frameView: {
      top: height * -1,
      left: width * 103,
      width: width * 190,
      gap: width * -38.5,
      zIndex: 20,
    },
    text22: {
      fontWeight: "600",
    },
    text23: {
      marginLeft: width * 39,
      fontWeight: "600",
    },
    parent8: {
      top: height * -1,
      left: width * 135,
      height: height * 26,
      width: width * 96,
      zIndex: 21,
    },
    frameChild1: {
      top: height * 64,
      left: width * 158,
      borderRadius: Border.br_9xs,
      backgroundColor: Color.colorGray_200,
      width: width * 55,
      height: height * 27,
      zIndex: 22,
      marginTop: height * 10,
      position: "absolute",
    },
    vs: {
      marginLeft: width * -7.5,
      top: height * 72.5,
      fontSize: FontSize.size_smi,
      lineHeight: height * 13,
      fontFamily: FontFamily.notoSansSemiBold,
      zIndex: 23,
      fontWeight: "600",
      marginTop: height * 10,
      textAlign: "center",
      left: "50%",
    },
    wrapper: {
      right: width * 15,
      zIndex: 24,
      top: height * 85,
      width: width * 100,
      marginTop: height * 10,
      position: "absolute",
    },
    frame: {
      left: width * 15,
      zIndex: 25,
      top: height * 85,
      width: width * 100,
      marginTop: height * 10,
      position: "absolute",
    },
    vectorParent: {
      justifyContent: "center",
      alignItems: "center",
      height: height * 293, 
    }
  });

  export default styles;