import { StyleSheet } from 'react-native';
import { width, height, Color, FontSize, FontFamily, Border } from "../GlobalStyles";

export const styles = StyleSheet.create({
    matchItem: {
      borderBottomWidth: 1,
      borderBottomColor: "#ccc",
      paddingVertical: 10,
      paddingHorizontal: 20,
    },
    mainInnerLayout: {
      height: height * 38,
      position: "absolute",
    },
    itemGroupLayout: {
      position: "absolute",
    },
    tablePosition: {
      left: width * 2,
      width: width * 371,
    },
    tableChildLayout: {
      height: height * 53,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: width * 371,
      position: "absolute",
    },
    pomChildPosition: {
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: 371,
    },
    pomLayout: {
      height: 44,
      position: "absolute",
    },
    mainChildLayout2: {
      width: 34,
      top: 218,
      backgroundColor: Color.colorDarkslategray,
      height: 40,
      position: "absolute",
    },
    textPosition1: {
      height: 16,
      textAlign: "left",
      left: "50%",
      position: "absolute",
    },
    wDLTypo: {
      top: height * 55,
      textAlign: "center",
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      color: Color.colorLightsteelblue_100,
      lineHeight: height * 12,
      fontSize: FontSize.size_xs,
      left: "50%",
      position: "absolute",
    },
    mainChildLayout1: {
      height: 12,
      width: 6,
      position: "absolute",
    },
    instanceLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    text4Layout: {
      width: 30,
      position: "absolute",
    },
    iconLayout3: {
      height: 20,
      position: "absolute",
    },
    shuTypo: {
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      top: 121,
      width: 30,
      textAlign: "center",
      lineHeight: 14,
      fontSize: FontSize.size_sm,
      height: 13,
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
    },
    plPosition: {
      marginLeft: -9,
      left: "50%",
      position: "absolute",
    },
    textTypo7: {
      marginLeft: width * -164.5,
      height: height * 17,
      width: width * 74,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textLayout1: {
      marginLeft: width * -160.5,
      width: width * 11,
      height: height * 18,
    },
    textTypo6: {
      top: height * 155,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo5: {
      top: height * 209.5,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textLayout: {
      width: width * 100,
      marginLeft: width * -81.5,
      height: height * 18,
    },
    textTypo4: {
      top: height * 99,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    mainChildLayout: {
      height: height * 9,
      width: width * 10,
      left: width * 47,
      position: "absolute",
    },
    fwTypo: {
      width: 98,
      height: 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: 17,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    fw1Typo: {
      top: 1263,
      width: 98,
      height: 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: 17,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    iconLayout2: {
      height: height * 30,
      position: "absolute",
    },
    textTypo3: {
      top: height * 265,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo2: {
      top: height * 320,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    iconLayout1: {
      height: height * 202,
      width: width * 174,
      top: height * 408,
      borderRadius: Border.br_3xs,
      position: "absolute",
    },
    iconLayout: {
      width: width * 174,
      top: height * 625,
      height: height * 202,
      borderRadius: Border.br_3xs,
      position: "absolute",
    },
    rectangleParentLayout: {
      height: height * 75,
      top: height * 535,
      width: width * 174,
      position: "absolute",
    },
    groupChildLayout3: {
      height: height * 56,
      width: width * 174,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      position: "absolute",
    },
    goalsTypo: {
      top: height * 546,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      textAlign: "left",
      color: Color.colorWhite,
      lineHeight: height * 16,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo1: {
      fontFamily: FontFamily.notoSansExtraBold,
      lineHeight: height * 36,
      fontSize: FontSize.size_17xl,
      top: height * 570,
      fontWeight: "800",
      textAlign: "left",
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
    },
    rectangleParentPosition: {
      top: height * 752,
      height: height * 75,
      width: width * 174,
      position: "absolute",
    },
    goals1Typo: {
      top: height * 763,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      textAlign: "left",
      color: Color.colorWhite,
      lineHeight: height * 16,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo: {
      top: height * 786,
      fontFamily: FontFamily.notoSansExtraBold,
      lineHeight: height * 36,
      fontSize: FontSize.size_17xl,
      fontWeight: "800",
      textAlign: "left",
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
    },
    dfTypo: {
      top: height * 1309,
      width: width * 98,
      height: height * 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: 16,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    df1Typo: {
      top: 1353,
      width: 98,
      height: 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: 16,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    mainChildPosition: {
      top: 1360,
      position: "absolute",
    },
    groupChildLayout2: {
      width: 14,
      left: 12,
      maxHeight: "100%",
      position: "absolute",
    },
    newsTypo: {
      color: Color.colorGray_300,
      fontFamily: FontFamily.notoSansRegular,
      lineHeight: 14,
      textAlign: "left",
      fontSize: FontSize.size_base,
    },
    groupPosition: {
      left: "50%",
      position: "absolute",
    },
    statsPosition: {
      marginLeft: -18,
      left: "50%",
      position: "absolute",
    },
    groupChildLayout1: {
      transform: [
        {
          rotate: "180deg",
        },
      ],
      borderRadius: Border.br_11xs,
      backgroundColor: Color.colorGray_300,
      width: 6,
      position: "absolute",
    },
    morePosition: {
      marginLeft: -19,
      left: "50%",
      position: "absolute",
    },
    groupChildLayout: {
      width: 7,
      height: 7,
      left: 15,
      position: "absolute",
    },
    image535Icon: {
      top: 1135,
      height: 40,
      width: 371,
      left: 3,
      position: "absolute",
    },
    image533Icon: {
      top: 0,
    },
    mainInner: {
      top: height * 42,
      backgroundColor: Color.colorGray_100,
      left: width * 2,
      width: width * 371,
    },
    tableChild: {
      top: height * -298,
    },
    tableItem: {
      top: height * -243,
    },
    tableInner: {
      top: height * -188,
    },
    rectangleView: {
      top: height * -133,
    },
    tableChild1: {
      top: height * -78,
    },
    table: {
      top: height * 380,
      height: height * 269,
      position: "absolute",
    },
    pomChild: {
      height: 71,
      top: 0,
      position: "absolute",
    },
    pomItem: {
      top: 73,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: 371,
    },
    pomInner: {
      top: 119,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: 371,
    },
    pomChild1: {
      top: 165,
      height: 38,
      position: "absolute",
    },
    pom: {
      top: 1177,
      height: 203,
      width: 371,
      left: 3,
      position: "absolute",
    },
    mainChild2: {
      left: 202,
    },
    mainChild3: {
      left: 106,
    },
    rank: {
      marginLeft: width * -171.5,
    },
    club: {
      marginLeft: width * -92.5,
    },
    wDL: {
      marginLeft: width * 42.5,
    },
    point: {
      marginLeft: width * 133.5,
    },
    groupChild: {
      backgroundColor: Color.colorCrimson,
      borderRadius: Border.br_8xs,
      height: 32,
      width: 148,
      marginLeft: -74.2,
      left: "50%",
      top: 0,
      position: "absolute",
    },
    rectangleParent: {
      top: 406,
      display: "none",
      height: 32,
      width: 148,
      marginLeft: -74.2,
      left: "50%",
      position: "absolute",
    },
    mainChild4: {
      top: height * 13,
      left: width * 65,
    },
    image514Icon: {
      top: height * 207,
      left: width * 74,
      width: width * 30,
    },
    image512Icon: {
      left: 111,
      width: 20,
    },
    group: {
      marginLeft: -131.5,
      width: 18,
    },
    groupView: {
      marginLeft: -93.5,
      width: 18,
    },
    mainInner1: {
      marginLeft: -74.5,
      width: 18,
    },
    ellipseIcon: {
      left: 212,
    },
    text16: {
      top: height * 12,
    },
    text17: {
      top: height * 98,
      width: width * 11,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      fontSize: FontSize.size_base,
      lineHeight: height * 18,
      marginLeft: width * -160.5,
      left: "50%",
      position: "absolute",
    },
    text18: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text19: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text20: {
      top: height * 98,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 19,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w6d2l: {
      marginLeft: width * 21.5,
    },
    text21: {
      marginLeft: width * 140,
    },
    text22: {
      top: height * 154,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 19,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w5d3l: {
      marginLeft: width * 21.5,
    },
    text23: {
      marginLeft: width * 139.5,
    },
    text24: {
      top: height * 209.5,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",   
    },
    w4d4l: {
      marginLeft: width * 21.5,
    },
    text25: {
      marginLeft: width * 140,
    },
    polygonIcon1: {
      top: height * 102,
    },
    polygonIcon2: {
      top: height * 158,
    },
    polygonIcon3: {
      top: height * 214,
    },
    jan2024: {
      top: 1202,
      width: 98,
      marginLeft: -163.5,
    },
    dec23: {
      marginLeft: -162.5,
    },
    image516Icon: {
      top: height * 97,
      left: width * 74,
      width: width * 30,
    },
    image517Icon: {
      top: height * 152,
      left: width * 74,
      width: width * 30,
    },
    text26: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text27: {
      top: height * 265,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w4d6l: {
      marginLeft: width * 21.5,
    },
    text28: {
      marginLeft: width * 140,
    },
    polygonIcon4: {
      top: height * 269,
    },
    text29: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text30: {
      top: height * 320,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w5d6l: {
      marginLeft: width * 21.5,
    },
    text31: {
      marginLeft: width * 140,
    },
    polygonIcon5: {
      top: height * 324,
    },
    image520Icon: {
      top: height * 262.5,
      left: width * 74,
      width: width * 30,
    },
    image521Icon: {
      top: height * 317,
      left: height * 74,
      width: width * 30,
    },
    text32: {
      top: height * 371,
    },
    mainChild12: {
      top: height * 373,
      left: width * 93,
    },
    image523Icon: {
      left: width * 191,
    },
    image526Icon: {
      left: width * 9,
    },
    image525Icon: {
      left: width * 9,
    },
    image524Icon: {
      left: width * 191,
    },
    groupChild9: {
      top: height * 20,
      borderRadius: Border.br_3xs,
    },
    groupChild10: {
      top: 0,
    },
    rectangleParent1: {
      left: width * 9,
    },
    rectangleParent2: {
      left: width * 191,
    },
    goals: {
      marginLeft: width * -116.5,
    },
    text33: {
      marginLeft: width * -116.5,
    },
    text34: {
      marginLeft: width * 69.5,
    },
    assists: {
      marginLeft: width * 64.5,
    },
    rectangleParent3: {
      left: width * 9,
    },
    rectangleParent4: {
      left: width * 191,
    },
    goals1: {
      marginLeft: width * -116.5,
    },
    text35: {
      marginLeft: width * -116.5,
    },
    text36: {
      marginLeft: width * 68.5,
    },
    cleanSheets: {
      marginLeft: width * 41.5,
    },
    pom1: {
      top: height * 1146,
      width: width * 161,
      marginLeft: width * -163.5,
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      fontSize: FontSize.size_base,
      lineHeight: height * 16,
    },
    mainChild13: {
      top: height * 1148,
      left: width * 66,
    },
    text37: {
      marginLeft: width * -46.5,
      top: height * 1206,
    },
    text38: {
      marginLeft: width * -64.5,
    },
    fw: {
      marginLeft: width * 147.5,
      top: height * 1202,
      width: width * 98,
    },
    fw1: {
      marginLeft: width * 148.5,
    },
    icon: {
      top: height * 1175,
      left: width * 241,
      width: width * 106,
      height: width * 73,
      position: "absolute",
    },
    image527Icon: {
      top: height * 1196,
      left: width * 104,
      height: height * 30,
    },
    image528Icon: {
      top: height * 1258,
      left: width * 92,
      width: width * 18,
    },
    df: {
      marginLeft: width * 148.5,
    },
    nov23: {
      marginLeft: width * -162.5,
    },
    text39: {
      marginLeft: width * -64.5,
    },
    image530Icon: {
      top: height * 1306,
      left: width * 91,
      width: width * 20,
    },
    df1: {
      marginLeft: width * 147.5,
    },
    nov231: {
      marginLeft: width * -163.5,
    },
    text40: {
      marginLeft: width * -65.5,
    },
    image531Icon: {
      top: height * 1350,
      left: width * 90,
      width: width * 20,
    },
    mainChild14: {
      left: width * -3,
      width: width * 390,
      height: height * 63,
      backgroundColor: Color.colorGray_200,
    },
    groupIcon: {
      height: "59.53%",
      bottom: "40.47%",
      left: "0%",
      right: "0%",
      top: "0%",
      width: "100%",
    },
    pl: {
      top: height * 29,
      lineHeight: height * 14,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      fontSize: FontSize.size_base,
    },
    groupParent: {
      height: "3.02%",
      width: "5.33%",
      top: "96.42%",
      right: "83.47%",
      bottom: "0.56%",
      left: "11.2%",
      position: "absolute",
    },
    groupChild17: {
      top: height * 12,
    },
    groupChild18: {
      top: height * 16,
    },
    groupChild19: {
      left: width * 12,
      top: height * 20,
      width: width * 10,
      maxHeight: "100%",
      position: "absolute",
    },
    news: {
      marginLeft: width * -19.5,
      top: height * 30,
      left: "50%",
      position: "absolute",
    },
    groupChild20: {
      borderWidth: width * 1.5,
      width: width * 22,
      borderColor: Color.colorGray_300,
      left: width * 8,
      borderStyle: "solid",
      borderRadius: Border.br_9xs,
      height: height * 26,
      top: 0,
      position: "absolute",
    },
    groupChild21: {
      left: width * 11,
      borderRadius: Border.br_12xs_5,
      width: width * 16,
      height: height * 7,
      backgroundColor: Color.colorGray_300,
      borderColor: Color.colorGray_300,
      borderWidth: width * 1,
      borderStyle: "solid",
      top: height * 3,
      position: "absolute",
    },
    vectorParent: {
      top: height * 1371,
      left: width * 119,
      width: width * 39,
    },
    stats: {
      color: Color.colorGray_300,
      fontFamily: FontFamily.notoSansRegular,
      lineHeight: height * 14,
      textAlign: "left",
      fontSize: FontSize.size_base,
      top: 0,
    },
    statsWrapper: {
      width: 36,
      top: 29,
      height: 14,
    },
    groupChild22: {
      height: 16,
      borderRadius: Border.br_11xs,
      top: 10,
      backgroundColor: Color.colorGray_300,
      width: 6,
      left: 0,
      position: "absolute",
    },
    groupChild23: {
      left: 13,
      height: 26,
      top: 0,
    },
    groupChild24: {
      top: 15,
      left: 20,
      height: 11,
    },
    rectangleParent5: {
      left: 8,
      width: 20,
      height: 26,
      top: 0,
      position: "absolute",
    },
    groupContainer: {
      marginLeft: 27.5,
      top: 1372,
      width: 36,
      height: 43,
    },
    more: {
      color: Color.colorGray_300,
      fontFamily: FontFamily.notoSansRegular,
      lineHeight: 14,
      textAlign: "left",
      fontSize: FontSize.size_base,
      top: 0,
    },
    moreWrapper: {
      top: 28,
      width: 38,
      height: 14,
    },
    groupChild25: {
      top: 0,
    },
    groupChild26: {
      top: 10,
      width: 7,
    },
    groupChild27: {
      top: 20,
    },
    groupParent1: {
      marginLeft: 120.5,
      top: 1373,
      height: 42,
      width: 38,
    },
    mainChild15: {
      backgroundColor: Color.colorKhaki,
      width: 85,
      height: 5,
      left: 3,
      top: 1360,
    },
    main: {
      flex: 1,
      width: "100%",    
      overflow: "hidden",
      backgroundColor: Color.colorGray_200,
      justifyContent: 'flex-start',  
    },
    fixture: {
      marginTop: 20,
    },
    matchInfo: {
      marginBottom: 20,
    },
    groupItem: {
      borderRadius: Border.br_8xs,
      height: height * 26,
      backgroundColor: Color.colorDarkslategray,     
      top: height * 0,
      left: width * 2,
      width: width * 371,
    },
    groupInner: {
      top: height * 14,
      backgroundColor: Color.colorDarkslategray,     
      height: height * 26,
      width: width * 371,
      left: width * 2,
    },
    groupItem1: {
      borderRadius: Border.br_8xs,
      height: height * 26,
      backgroundColor: Color.colorDarkslategray,     
      top: height * 359,
      left: width * 2,
      width: width * 371,
    },
    groupInner1: {
      top: height * 373,
      backgroundColor: Color.colorDarkslategray,     
      height: height * 26,
      width: width * 371,
      left: width * 2,
    },

    main1: {
      flex: 1,
      height: '100%',
      overflow: "hidden",
      width: "100%",    
      backgroundColor: Color.colorGray_200,
      justifyContent: 'flex-end',  
    },
    container: {
      flexGrow: 1, // Allow content to grow to fill the container
      justifyContent: "center", // Center content vertically
      alignItems: "center", // Center content horizontally
    },
  });

  export default styles;