import { StyleSheet } from 'react-native';
import { width, height, Color, FontSize, FontFamily, Border } from "../GlobalStyles";

export const styles = StyleSheet.create({
    matchItem: {
      borderBottomWidth: width * 1,
      borderBottomColor: "#ccc",
      paddingVertical: width * 10,
      paddingHorizontal: height * 20,
    },
    mainInnerLayout: {
      height: height * 38,
      position: "absolute",
    },
    itemGroupLayout: {
      position: "absolute",
    },
    tablePosition: {
      left: width * 2,
      width: width * 371,
    },
    tableChildLayout: {
      height: height * 53,
      left: width * 2,
      backgroundColor: Color.colorDarkslategray,
      width: width * 371,
    },
    touch1: {
      height: height * 53,
      left: width * 2,
      top: height * 434,
      backgroundColor: Color.colorWhite,
      zIndex : 999,
      width: width * 371,
    },
    pomChildPosition: {
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: width * 371,
    },
    pomLayout: {
      height: height * 44,
      position: "absolute",
    },
    mainChildLayout2: {
      width: width * 34,
      top: height * 218,
      backgroundColor: Color.colorDarkslategray,
      height: height * 40,
      position: "absolute",
    },
    textPosition1: {
      height: height * 16,
      textAlign: "left",
      left: "48%",
      position: "absolute",
    },
    wDLTypo: {
      top: height * 55,
      textAlign: "center",
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      color: Color.colorLightsteelblue_100,
      lineHeight: height * 12,
      fontSize: FontSize.size_xs,
      left: "50%",
      position: "absolute",
    },
    mainChildLayout1: {
      height: height * 12,
      width: width * 7,
      position: "absolute",
    },
    text4Layout: {
      width: width * 30,
      position: "absolute",
    },
    iconLayout3: {
      height: height * 22,
      position: "absolute",
    },
    shuTypo: {
      fontFamily: FontFamily.notoSansBold,
      fontWeight: "700",
      top: height * 121,
      width: width * 30,
      textAlign: "center",
      lineHeight: height * 14,
      fontSize: FontSize.size_sm,
      height: height * 13,
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
    },
    textTypo7: {
      marginLeft: width * -164.5,
      height: height * 20,
      width: width * 74,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "48%",
      position: "absolute",
    },
    textLayout1: {
      marginLeft: width * -160.5,
      width: width * 11,
      height: height * 20,
      zIndex: 1
    },
    textTypo6: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo5: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textLayout: {
      width: width * 100,
      marginLeft: width * -86.5,
      letterSpacing: width *-0.3,
      height: height * 21,
    },
    textTypo4: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position : "absolute",
      zIndex : 1
    },
    mainChildLayout: {
      height: height * 9,
      width: width * 10,
      left: width * 47,
      position: "absolute",
    },
    fwTypo: {
      width: width * 98,
      height: height * 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 19,
      fontSize: FontSize.size_base,
      left: "48%",
      position: "absolute",
    },
    fw1Typo: {
      top: height * 964,
      width: width * 150,
      height: height * 20,
      textAlign: "center",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "36%",
      position: "absolute",
    },
    iconLayout2: {
      height: height * 22,
      position: "absolute",
    },
    textTypo3: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo2: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    iconLayout1: {
      height: height * 202,
      width: width * 174,
      bottom: height * 480,
      borderRadius: Border.br_3xs,
      position: "absolute",
    },
    iconLayout: {
      width: width * 174,
      bottom: height * 264,
      height: height * 202,
      borderRadius: Border.br_3xs,
      position: "absolute",
    },
    rectangleParentLayout: {
      height: height * 75,
      top: height * 535,
      width: width * 174,
      position: "absolute",
    },
    groupChildLayout3: {
      height: height * 56,
      width: width * 174,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      position: "absolute",
    },
    goalsTypo: {
      top: height * 544,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      textAlign: "center",
      color: Color.colorWhite,
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo1: {
      fontFamily: FontFamily.notoSansExtraBold,
      lineHeight: height * 36,
      fontSize: FontSize.size_17xl,
      top: height * 570,
      fontWeight: "800",
      textAlign: "left",
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
    },
    rectangleParentPosition: {
      top: height * 752,
      height: height * 75,
      width: width * 174,
      position: "absolute",
    },
    goals1Typo: {
      top: height * 761,
      fontFamily: FontFamily.notoSansMedium,
      fontWeight: "500",
      textAlign: "center",
      color: Color.colorWhite,
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "50%",
      position: "absolute",
    },
    textTypo: {
      top: height * 787,
      fontFamily: FontFamily.notoSansExtraBold,
      lineHeight: height * 36,
      fontSize: FontSize.size_17xl,
      fontWeight: "800",
      textAlign: "left",
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
    },
    dfTypo: {
      top: height * 1010.5,
      width: width * 98,
      height: height * 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "48%",
      position: "absolute",
    },
    df1Typo: {
      top: height * 1057,
      width: width * 98,
      height: height * 20,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "48%",
      position: "absolute",
    },
    mainChildPosition: {
      top: height * 1360,
      position: "absolute",
    },
    groupChildLayout2: {
      width: width * 14,
      left: width * 12,
      maxHeight: "100%",
      position: "absolute",
    },
    image535Icon: {
      top: height * 836,
      height: height * 40,
      width: width * 371,
      left: width * 3,
      position: "absolute",
    },
    image533Icon: {
      top: 0,
    },
    mainInner: {
      top: height * 42,
      backgroundColor: Color.colorGray_100,
      left: width * 2,
      width: width * 371,
    },
    tableChild: {
      bottom: height * 742,
    },
    tableItem: {
      bottom: height * 740,
    },
    tableInner: {
      bottom: height * 738,
    },
    rectangleView: {
      bottom: height * 736,
    },
    tableChild1: {
      bottom: height * 734,
    },
    table: {
      top: height * 380,
      height: height * 269,
      position: "absolute",
    },
    pomChild: {
      height: height * 71,
      top: 0,
      position: "absolute",
    },
    pomItem: {
      top: height * 73,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: width * 371,
    },
    pomInner: {
      top: height * 119,
      left: 0,
      backgroundColor: Color.colorDarkslategray,
      width: width * 371,
    },
    pomChild1: {
      top: height * 165,
      height: height * 44,
      position: "absolute",
    },
    pom: {
      top: height * 878,
      height: height * 203,
      width: width * 371,
      left: width * 3,
      position: "absolute",
    },
    mainChild2: {
      left: width * 202,
    },
    mainChild3: {
      left: width * 106,
    },
    rank: {
      marginLeft: width * -171.5,
    },
    club: {
      marginLeft: width * -92.5,
    },
    wDL: {
      marginLeft: width * 42.5,
    },
    point: {
      marginLeft: width * 133.5,
    },
    groupChild: {
      backgroundColor: Color.colorCrimson,
      borderRadius: Border.br_8xs,
      height: height * 32,
      width: width * 148,
      marginLeft: width * -74.2,
      left: "50%",
      top: 0,
      position: "absolute",
    },
    rectangleParent: {
      top: height * 406,
      display: "none",
      height: height * 32,
      width: width * 148,
      marginLeft: width * -74.2,
      left: "50%",
      position: "absolute",
    },
    mainChild4: {
      top: height * 14,
      left: width * 65,
    },
    image514Icon: {
      top: height * 17,
      left: width * 72,
      width: width * 30,
    },
    image512Icon: {
      left: width * 111,
      width: width * 20,
    },
    group: {
      marginLeft: width * -131.5,
      width: width * 18,
    },
    groupView: {
      marginLeft: width * -93.5,
      width: width * 18,
    },
    mainInner1: {
      marginLeft: width * -74.5,
      width: width * 18,
    },
    ellipseIcon: {
      left: width * 212,
    },
    text16: {
      top: height * 11,
    },
    text17: {
      top: height * 19,
      width: width * 11,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      fontSize: FontSize.size_base,
      lineHeight: height * 18,
      marginLeft: width * -160.5,
      left: "50%",
      position: "absolute",
    },
    text18: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text19: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text20: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 19,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w6d2l: {
      marginLeft: width * 21.5,
    },
    text21: {
      marginLeft: width * 140,
    },
    text22: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 19,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w5d3l: {
      marginLeft: width * 21.5,
    },
    text23: {
      marginLeft: width * 139.5,
    },
    text24: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",   
    },
    w4d4l: {
      marginLeft: width * 21.5,
    },
    text25: {
      marginLeft: width * 140,
    },
    polygonIcon1: {
      top: height * 23,
    },
    polygonIcon2: {
      top: height * 23,
    },
    polygonIcon3: {
      top: height * 23,
    },
    jan2024: {
      top: height * 905,
      width: width * 98,
      marginLeft: width * -163.5,
    },
    dec23: {
      marginLeft: width * -163.5,
      width: width * 98,
    },
    image516Icon: {
      top: height * 17,
      left: width * 72,
      width: width * 30,
    },
    image517Icon: {
      top: height * 17,
      left: width * 72,
      width: width * 30,
    },
    text26: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text27: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w4d6l: {
      marginLeft: width * 21.5,
    },
    text28: {
      marginLeft: width * 140,
    },
    polygonIcon4: {
      top: height * 23,
    },
    text29: {
      width: width * 11,
      marginLeft: width * -160.5,
      height: height * 18,
    },
    text30: {
      top: height * 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      lineHeight: height * 18,
      fontSize: FontSize.size_base,
      left: "51.5%",
      position: "absolute",
    },
    w5d6l: {
      marginLeft: width * 21.5,
    },
    text31: {
      marginLeft: width * 140,
    },
    polygonIcon5: {
      top: height * 23,
    },
    image520Icon: {
      top: height * 17,
      left: width * 72,
      width: width * 30,
    },
    image521Icon: {
      top: height * 17,
      left: height * 72,
      width: width * 30,
    },
    text32: {
      bottom: height * 698,
    },
    mainChild12: {
      bottom: height * 704,
      left: width * 93,
    },
    image523Icon: {
      left: width * 191,
    },
    image526Icon: {
      left: width * 9,
    },
    image525Icon: {
      left: width * 9,
    },
    image524Icon: {
      left: width * 191,
    },
    groupChild9: {
      top: height * 20,
      borderRadius: Border.br_3xs,
    },
    groupChild10: {
      top: 0,
    },
    rectangleParent1: {
      left: width * 9,
    },
    rectangleParent2: {
      left: width * 191,
    },
    goals: {
      marginLeft: width * -124.5,
    },
    text33: {
      marginLeft: width * -116.5,
    },
    text34: {
      marginLeft: width * 69.5,
    },
    assists: {
      marginLeft: width * 64.5,
    },
    rectangleParent3: {
      left: width * 9,
    },
    rectangleParent4: {
      left: width * 191,
    },
    goals1: {
      marginLeft: width * -119.5,
    },
    text35: {
      marginLeft: width * -116.5,
    },
    text36: {
      marginLeft: width * 68.5,
    },
    cleanSheets: {
      marginLeft: width * 57.5,
    },
    pom1: {
      top: height * 849,
      width: width * 161,
      marginLeft: width * -163.5,
      color: Color.colorWhite,
      fontFamily: FontFamily.notoSansSemiBold,
      fontWeight: "600",
      fontSize: FontSize.size_base,
      lineHeight: height * 18,
    },
    mainChild13: {
      top: height * 851.5,
      left: width * 110,
    },
    text37: {
      marginLeft: width * -45.5,
      top: height * 905,
    },
    text38: {
      marginLeft: width * -40.5,
    },
    fw: {
      marginLeft: width * 147.5,
      top: height * 905,
      width: width * 98,
    },
    fw1: {
      marginLeft: width * 130,
    },
    icon: {
      top: height * 876,
      left: width * 230,
      width: width * 106,
      height: height * 73,
      position: "absolute",
    },
    image527Icon: {
      top: height * 899,
      left: width * 91,
      height: height * 30,
    },
    image528Icon: {
      top: height * 961,
      left: width * 95,
      width: width * 22,
    },
    df: {
      marginLeft: width * 147.5,
    },
    nov23: {
      marginLeft: width * -163.5,
    },
    text39: {
      marginLeft: width * -47.5,
    },
    image530Icon: {
      top: height * 1008,
      left: width * 95,
      width: width * 22,
    },
    df1: {
      marginLeft: width * 147.5,
    },
    nov231: {
      marginLeft: width * -163.5,
    },
    text40: {
      marginLeft: width * -47.5,
    },
    image531Icon: {
      top: height * 1053,
      left: width * 95,
      width: width * 22,
    },
    mainChild14: {
      left: width * -3,
      width: width * 390,
      height: height * 63,
      backgroundColor: Color.colorGray_200,
    },
    groupChild17: {
      top: height * 12,
    },
    groupChild18: {
      top: height * 16,
    },
    groupChild19: {
      left: width * 12,
      top: height * 20,
      width: width * 10,
      maxHeight: "100%",
      position: "absolute",
    },
    groupContainer: {
      marginLeft: width * 27.5,
      top: height * 1372,
      width: width * 36,
      height: height * 43,
    },
    main: {
      height : height * 1382,
      width: "100%",    
      overflow: "hidden",
      backgroundColor: Color.colorGray_200,
      justifyContent: 'flex-start',  
    },
    fixture: {
      marginTop: height * 20,
    },
    matchInfo: {
      marginBottom: height * 20,
    },
    groupItem: {
      borderRadius: Border.br_8xs,
      height: height * 26,
      backgroundColor: Color.colorDarkslategray,     
      top: height * 0,
      left: width * 2,
      width: width * 371,
    },
    groupInner: {
      top: height * 14,
      backgroundColor: Color.colorDarkslategray,     
      height: height * 26,
      width: width * 371,
      left: width * 2,
    },
    groupItem1: {
      borderRadius: Border.br_8xs,
      height: height * 26,
      backgroundColor: Color.colorDarkslategray,     
      top: height * 359,
      left: width * 2,
      width: width * 371,
    },
    groupInner1: {
      top: height * 373,
      backgroundColor: Color.colorDarkslategray,     
      height: height * 26,
      width: width * 371,
      left: width * 2,
    },
    navi1: {
      top: height * 5,
      width: width * 100,
      height: height * 27,
      zIndex: 999,
      left: width * 2,
      position: "absolute"
      },
      navi2: {
        bottom: height * 805,
        width: width * 371,
        height: height * 40,
        zIndex: 999,
        left: width * 0,
        backgroundColor: Color.colorWhite,
        },  
    main1: {
      flex: 1,
      height: '100%',
      overflow: "hidden",
      width: "100%",    
      backgroundColor: Color.colorGray_200,
      justifyContent: 'flex-end',  
    },
    container: {
      flexGrow: 1, // Allow content to grow to fill the container
      justifyContent: "center", // Center content vertically
      alignItems: "center", // Center content horizontally
    },
  });

  export default styles;